---

- name: Apt | Update cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"
  changed_when: false
  tags:
    - apt

- name: Apt | Install packages
  ansible.builtin.apt:
    pkg: "{{ apt_install_packages }}"
    state: present
  tags:
    - apt

- name: Apt | Remove packages
  ansible.builtin.apt:
    pkg: "{{ apt_remove_packages }}"
    purge: true
    state: absent
  tags:
    - apt
