version: 2.1
# Define the jobs we want to run for this project
jobs:
 # Test
 test:
   machine:
     image: ubuntu-2004:202010-01
   steps:
     - checkout
     - run:
         name: Install Docker
         command: |
           sudo apt-get install apt-transport-https ca-certificates curl gnupg lsb-release
           curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
           echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
           sudo apt-get update
           sudo apt-get install docker-ce docker-ce-cli containerd.io
     - run:
         name: Install Dependancies
         command: |  
           sudo apt update -y -qq
           sudo apt install -y -qq python3-pip
           # Install dependancies
           pip3 install -r requirements.txt
           # Check ansible version
           ansible --version
           # Check molecule version
           molecule --version
     - run:
         name: Molecule Tests
         command: |
           # Symlink project folder
           ln -s /home/circleci/project /etc/ansible/roles/${CIRCLE_PROJECT_REPONAME}
           # Run tests
           molecule test
     - store_test_results:
         path: test-results
 # Release
 release:
   docker:
     - image: ubuntu:18.04
   steps:
     - checkout
     - run:
         name: Install Dependancies
         command: |  
           apt update -y -qq
           apt install -y -qq git
     - run:
         name: Run release
         command: |
           ./circleci.sh --release
     - store_test_results:
         path: test-results
     - store_artifacts:
         path: test-results
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
  build_and_release:
    when:
      and:
        - equal: [ master, << pipeline.git.branch >> ]
        - equal: [ "", << pipeline.git.tag >> ]
    jobs:
      - release:
          requires:
            - test
