---
- name: Converge
  hosts: all
  tasks:

    - name: Converge | Including vars main.yml
      ansible.builtin.include_vars: vars/main.yml

    - name: Converge | Include ansible-role-apt
      ansible.builtin.include_role:
        name: ansible-role-apt
