---
- name: Converge
  hosts: all
  tasks:
    - name: Including vars main.yml
      include_vars: vars/main.yml

    - name: "Include ansible-role-..."
      include_role:
        name: "ansible-role-..."
