---
driver:
  name: docker

platforms:
  - name: default_instance
    image: geerlingguy/docker-ubuntu2404-ansible
    pre_build_image: true

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../ # Set so ansible can find the role

verifier:
  name: ansible

scenario:
  create_sequence:
    - create      # Use the provisioner to start the instances.
    - prepare     # Use the provisioner to prepare the instances into a particular starting state.
  converge_sequence:
    - create
    - prepare
    - converge    # Use the provisioner to configure instances
  check_sequence:
    - create
    - prepare
    - converge
    - check       # Use the provisioner to perform a Dry-Run
    - destroy     # Use the provisioner to destroy the instances.
  destroy_sequence:
    - destroy
  test_sequence:
    - syntax      # Use the provisioner to syntax check the role.
    - create
    - prepare
    - converge
    - idempotence # Use the provisioner to configure the instances (Second provision after converge)
    - verify      # Run automated tests against instances.
    - destroy
