---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:

    - name: Verify | Including vars main.yml
      ansible.builtin.include_vars: vars/main.yml

    - name: Verify | Include tests
      ansible.builtin.include_tasks: "{{ item }}"
      with_fileglob:
        - tests/*.yml
...
